[package]
name = "atm"
version = "0.3.0"
authors = ["All The Music, LLC"]
edition = "2018"

[dependencies]
flate2 = "1.0.9"
itertools = "0.8.0"
libatm = { path = "lib/libatm" }
pbr = "1.0.1"
structopt = "0.3.9"
tar = "0.4.26"
thiserror = "1.0.11"
